### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Seluj78** [Azahet/BombParty-Helper#1]
Can you provide installation and usage information ?

**Comment by Azahet** [comment]
Launch the program and write the 2 letter ask bombparty
Bombparty helper put automaticly the first word in u'r clipboard
And paste-it on the game

**Comment by Seluj78** [comment]
Yeah thanks I had this part figured out, I was talking about the clone itself, how so you install it? What do you run ? What file ? Etc... Like a proper readme

**Comment by Azahet** [comment]
I do crap with csproj so just copy the program.cs in a new app.
just you need two dependence: Windows.form, colorfull.consol

**Comment by Seluj78** [comment]
Is there any way you can be more descriptive ?

I really like the idea of your project but if you want more people to use it, you need a readme with detailed instructions on how to install, launch and use your code

I'm really not trying to be mean here, but you are not really helping ;)

**Comment by Azahet** [comment]
It's just a console app with 10 lines of code. I think it's not that hard to understand the function. You clone, you compile and you throw.
It's .net after if you do not know dev in .net I can not help you :/

**Comment by Seluj78** [comment]
Dude are you really serious ? 

`If you cant explain how to start a .net program` then you cannot be helped...
So long and no thanks for all the fish
